# Generated by Django 5.1.3 on 2024-11-09 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag_alter_video_options_alter_video_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
